### ISSUE TITLE
no #no_std useful tag

### ISSUE THREAD

**Issue by boshtannik** [LukaOber/serialmessage-rs#1]
https://github.com/LukaOber/serialmessage-rs/blob/070c1945857a5bc57b87849951ccfd3117b5a7e7/README.md?plain=1#L75

On crates.io there is no mention #no_std tag. Many people do use tags to find libraries. I even could skip attention to  this library, because no #no_std was mention in the header. Add it.

**Comment by LukaOber** [comment]
Sorry for the super late response. I added the tag and published a new version. Thanks for the suggestion.
